"""empty message

Revision ID: 07714731069f
Revises: 6f8afc870f54
Create Date: 2024-10-12 12:15:46.214073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07714731069f'
down_revision: Union[str, None] = '6f8afc870f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_sessions', sa.Column('refresh_token_id', sa.UUID(), nullable=False))
    op.drop_column('gptranslate_sessions', 'token_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_sessions', sa.Column('token_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('gptranslate_sessions', 'refresh_token_id')
    # ### end Alembic commands ###
