"""empty message

Revision ID: 2618fbd95c8c
Revises: 07714731069f
Create Date: 2024-10-12 14:12:05.933295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2618fbd95c8c'
down_revision: Union[str, None] = '07714731069f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gptranslate_sessions_user_id_fkey', 'gptranslate_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'gptranslate_sessions', 'gptranslate_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gptranslate_sessions', type_='foreignkey')
    op.create_foreign_key('gptranslate_sessions_user_id_fkey', 'gptranslate_sessions', 'gptranslate_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
