"""empty message

Revision ID: 41f3a138202f
Revises: de2f4ad24c71
Create Date: 2024-10-20 19:49:07.643399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41f3a138202f'
down_revision: Union[str, None] = 'de2f4ad24c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_configs', sa.Column('language_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
    op.add_column('gptranslate_configs', sa.Column('model_id', sa.Integer(), nullable=True))
    op.alter_column('gptranslate_configs', 'prompt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('gptranslate_configs_report_id_fkey', 'gptranslate_configs', type_='foreignkey')
    op.drop_constraint('gptranslate_configs_language_id_fkey', 'gptranslate_configs', type_='foreignkey')
    op.create_foreign_key(None, 'gptranslate_configs', 'gptranslate_ai_models', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_column('gptranslate_configs', 'report_id')
    op.drop_column('gptranslate_configs', 'language_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_configs', sa.Column('language_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('gptranslate_configs', sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gptranslate_configs', type_='foreignkey')
    op.create_foreign_key('gptranslate_configs_language_id_fkey', 'gptranslate_configs', 'gptranslate_reports', ['language_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('gptranslate_configs_report_id_fkey', 'gptranslate_configs', 'gptranslate_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.alter_column('gptranslate_configs', 'prompt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('gptranslate_configs', 'model_id')
    op.drop_column('gptranslate_configs', 'language_ids')
    # ### end Alembic commands ###
