"""empty message

Revision ID: 4a971161cfe8
Revises: 2618fbd95c8c
Create Date: 2024-10-12 14:27:23.941606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a971161cfe8'
down_revision: Union[str, None] = '2618fbd95c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_sessions', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.drop_column('gptranslate_sessions', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_sessions', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('gptranslate_sessions', 'closed_at')
    # ### end Alembic commands ###
