"""empty message

Revision ID: 739172bb9c0e
Revises: 41f3a138202f
Create Date: 2024-10-22 10:23:47.011519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739172bb9c0e'
down_revision: Union[str, None] = '41f3a138202f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_ai_models', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('gptranslate_ai_models', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('gptranslate_translation_tasks', sa.Column('prompt_id', sa.Integer(), nullable=False))
    op.add_column('gptranslate_translation_tasks', sa.Column('model_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gptranslate_translation_tasks', 'gptranslate_ai_models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gptranslate_translation_tasks', 'gptranslate_style_prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gptranslate_translation_tasks', type_='foreignkey')
    op.drop_constraint(None, 'gptranslate_translation_tasks', type_='foreignkey')
    op.drop_column('gptranslate_translation_tasks', 'model_id')
    op.drop_column('gptranslate_translation_tasks', 'prompt_id')
    op.drop_column('gptranslate_ai_models', 'deleted_at')
    op.drop_column('gptranslate_ai_models', 'created_at')
    # ### end Alembic commands ###
