"""empty message

Revision ID: 954d79f4956d
Revises: 08e8f51e306a
Create Date: 2024-10-24 08:08:11.580491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954d79f4956d'
down_revision: Union[str, None] = '08e8f51e306a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_sessions', sa.Column('user_agent', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gptranslate_sessions', 'user_agent')
    # ### end Alembic commands ###
