"""empty message

Revision ID: c3cd88862564
Revises: f78c0837b3d8
Create Date: 2024-10-19 17:10:20.026021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cd88862564'
down_revision: Union[str, None] = 'f78c0837b3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gptranslate_ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gptranslate_translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('source_lang', sa.Integer(), nullable=True),
    sa.Column('target_lang', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['gptranslate_style_prompts.id'], ),
    sa.ForeignKeyConstraint(['source_lang'], ['gptranslate_languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_lang'], ['gptranslate_languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gptranslate_translation')
    op.drop_table('gptranslate_ai_models')
    # ### end Alembic commands ###
