"""empty message

Revision ID: de2f4ad24c71
Revises: c3cd88862564
Create Date: 2024-10-20 10:50:30.128415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de2f4ad24c71'
down_revision: Union[str, None] = 'c3cd88862564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_translation_tasks', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional data related to the translation task (e.g., errors or metadata)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gptranslate_translation_tasks', 'data')
    # ### end Alembic commands ###
