"""empty message

Revision ID: f78c0837b3d8
Revises: 7c7c17346671
Create Date: 2024-10-14 12:14:28.592857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78c0837b3d8'
down_revision: Union[str, None] = '7c7c17346671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_reports', sa.Column('reason_id', sa.Integer(), nullable=False))
    op.alter_column('gptranslate_reports', 'closed_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('gptranslate_reports_original_article_id_fkey', 'gptranslate_reports', type_='foreignkey')
    op.create_foreign_key(None, 'gptranslate_reports', 'gptranslate_report_reasons', ['reason_id'], ['id'], ondelete='CASCADE')
    op.drop_column('gptranslate_reports', 'original_article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gptranslate_reports', sa.Column('original_article_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gptranslate_reports', type_='foreignkey')
    op.create_foreign_key('gptranslate_reports_original_article_id_fkey', 'gptranslate_reports', 'gptranslate_articles', ['original_article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('gptranslate_reports', 'closed_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('gptranslate_reports', 'reason_id')
    # ### end Alembic commands ###
