services:
  api:
    image: diploma-base
    build:
      context: ../..
      dockerfile: contrib/docker/fastapi/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - ./fastapi/docker-entrypoint.d:/app/docker-entrypoint.d
    depends_on:
      - postgres
    networks:
      - a

  postgres:
    build:
      context: ../../
      dockerfile: contrib/docker/postgres/Dockerfile
    restart: always
    env_file:
      - ../../.env
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    networks:
      - a

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_ADDRESS}
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_ADDRESS}
      KAFKA_SESSION_TIMEOUT_MS: 360000
      KAFKA_MAX_POLL_INTERVAL_MS: 3600000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - a

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - a

  translation_consumer:
    image: diploma-base
    command:
      - "python"
      - "-m"
      - "src.manage"
      - "start_translator_consumer"
    env_file:
      - ../../.env
    volumes:
      - ./consumer/docker-entrypoint.d:/app/docker-entrypoint.d
    depends_on:
      - kafka
    networks:
      - a

  mail_consumer:
    image: diploma-base
    command:
      - "python"
      - "-m"
      - "src.manage"
      - "start_mail_consumer"
    env_file:
      - ../../.env
    volumes:
      - ./consumer/docker-entrypoint.d:/app/docker-entrypoint.d
    depends_on:
      - kafka
    networks:
      - a

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    restart: always
    networks:
      - a

  nginx:
    build:
      context: ../..
      dockerfile: contrib/docker/nginx/Dockerfile
    ports:
      - "8000:8000"
#      - "8080:9000"
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - a

  vue-dev:
    build:
      context: ../..
      dockerfile: contrib/docker/vue-dev/Dockerfile
    volumes:
      - ../front/:/app
    command:
      - "npm"
      - "run"
      - "dev"
      - "--"
      - "--host"
      - "0.0.0.0"
    networks:
      - a


volumes:
  pg_data:
    driver: local

networks:
  a:
    external: true
