services:
  api:
    build:
      context: ../..
      dockerfile: contrib/docker/fastapi/Dockerfile
    environment:
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DB_POOL_SIZE: ${DB_POOL_SIZE}
      DB_MAX_OVERFLOW: ${DB_MAX_OVERFLOW}
      DB_POOL_RECYCLE: ${DB_POOL_RECYCLE}
      DB_POOL_PRE_PING: ${DB_POOL_PRE_PING}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app
    networks:
      - a


networks:
  a:
    external: true