services:
  api:
    build:
      context: ../..
      dockerfile: contrib/docker/fastapi/Dockerfile
#    environment:
#      APP_SECRET_KEY: ${APP_SECRET_KEY}
#      DATABASE_URL: ${DATABASE_URL}
#      DB_POOL_SIZE: ${DB_POOL_SIZE}
#      DB_MAX_OVERFLOW: ${DB_MAX_OVERFLOW}
#      DB_POOL_RECYCLE: ${DB_POOL_RECYCLE}
#      DB_POOL_PRE_PING: ${DB_POOL_PRE_PING}
#      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app
    depends_on:
      - postgres

  postgres:
    build:
      context: ../../
      dockerfile: contrib/docker/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_ADDRESS}
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_ADDRESS}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_ADDRESS}
      JVM_OPTS: '-Xmx256M'
    depends_on:
      - kafka

  translation_consumer:
    image: diploma-base
    command:
      - "python"
      - "-m"
      - "src.manage"
      - "start_translator_consumer"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      NOTIFICATION_ADDRESS: ${NOTIFICATION_ADDRESS}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_PROJECT_ID: ${GEMINI_PROJECT_ID}
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
      TRANSLATION_KAFKA_TOPIC: ${TRANSLATION_KAFKA_TOPIC}
      TRANSLATION_TASK_MAX_RETRIES: ${TRANSLATION_TASK_MAX_RETRIES:-5}
      RESEND_MESSAGE_MAX_RETRIES: ${RESEND_MESSAGE_MAX_RETRIES:-100}
    volumes:
      - ./consumer/docker-entrypoint.d:/app/docker-entrypoint.d
    depends_on:
      - kafka

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    restart: always


volumes:
  pg_data:
    driver: local