gnome-terminal -- bash -c "node server.js 0; exec bash"
gnome-terminal -- bash -c "node server.js 1; exec bash"
gnome-terminal -- bash -c "node server.js 2; exec bash"
gnome-terminal -- bash -c "node server.js 3; exec bash"
gnome-terminal -- bash -c "node server.js 4; exec bash"
gnome-terminal -- bash -c "node server.js 5; exec bash"
gnome-terminal -- bash -c "node server.js 6; exec bash"
gnome-terminal -- bash -c "node intermediary.js; exec bash"